# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'log of aspirin'
tagline:          'Hopefully something useful will come of this.'
description:      'all work and all play'
url:              https://aspirin-.github.io
baseurl:          /

author:
  name:           'Seth Leick'
  url:            https://twitter.com/sethll

paginate:         5

# Custom vars
# version:          2.1.0

github:
    repo:           https://github.com/aspirin-/aspirin-.github.io
